# Generated by Django 4.1.1 on 2022-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='charity_email',
            field=models.CharField(default='charityemail', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='charity_website',
            field=models.TextField(default='charitywebsite'),
        ),
        migrations.AddField(
            model_name='post',
            name='donation_goal',
            field=models.CharField(default='10000', max_length=255),
        ),
    ]
