# Generated by Django 4.1 on 2022-10-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_charity_email_post_charity_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='charity_type',
            field=models.CharField(choices=[('EV', 'environment'), ('ED', 'education'), ('CC', 'child care'), ('HC', 'healthcare'), ('AN', 'animals'), ('DV', 'domestic violence'), ('HL', 'homeless services'), ('NU', 'nutrition'), ('MV', 'military veterans')], default='EV', max_length=2),
        ),
    ]
