# Generated by Django 4.1.1 on 2022-09-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.CharField(default='0', max_length=255)),
                ('charity_name', models.CharField(default='charityname', max_length=255)),
            ],
        ),
    ]
